# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

objective_manifold <- function(x, D, K, N, stiefel_dim, total_dim, orthB_list, y_vec_list, orthP, lambda, tau, ridge_weights) {
    .Call(`_prodMCG_objective_manifold`, x, D, K, N, stiefel_dim, total_dim, orthB_list, y_vec_list, orthP, lambda, tau, ridge_weights)
}

gradient_manifold <- function(x, D, K, N, stiefel_dim, total_dim, orthB_list, y_vec_list, orthP, lambda, tau, ridge_weights) {
    .Call(`_prodMCG_gradient_manifold`, x, D, K, N, stiefel_dim, total_dim, orthB_list, y_vec_list, orthP, lambda, tau, ridge_weights)
}

